on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3

      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOCKERUSERNAME}} --password ${{ secrets.DOCKERPASS }}
      - name: " building docker "
        run: docker build -t ${{ secrets.DOCKERUSERNAME}}/taskjava .
      - name: " pushing to docker hub "
        run: docker push ${{ secrets.DOCKERUSERNAME}}/taskjava
